### PR TITLE
Update to Node.js 14.x runtime

### PR DESCRIPTION
**Pull request by eduardomourar**
*Issue #, if available:*

*Description of changes:* Update to Node.js 14.x runtime

Related to issue: https://github.com/aws-cloudformation/cloudformation-cli/pull/746

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by ammokhov — APPROVED** [review]

**Review by PatMyron — APPROVED** [review]

**Comment by RichiCoder1** [comment]
Howdy! With Node.js 12.x deprecation looming, what are the chances of getting this (and hopefully #67) merged?

**Review by ammokhov — APPROVED** [review]
Approved but could you plz address warnings

**Comment by gsurbhi** [comment]
Looks good to me but there are bunch of warning

**Comment by gsurbhi** [comment]
Could you fix this warning: Unexpected any. Specify a different type

**Comment by ammokhov** [comment]
closing as this is a dup of #71

**Pull request closed without merging**
